In [1]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [10, 10, 10],
    [1, 1, 2],
    [3, 4, 5]
])

In [2]:
type(A)

numpy.ndarray

In [3]:
A.size

9

In [4]:
suma1 = A + B

In [5]:
A - B

array([[-9, -8, -7],
       [ 3,  4,  4],
       [ 4,  4,  4]])

In [6]:
# A x B
# 21 24 29
# 63 69 80
# 105 114 131

In [7]:
# Element-wise

A * B

array([[10, 20, 30],
       [ 4,  5, 12],
       [21, 32, 45]])

In [8]:
A @ B

array([[ 21,  24,  29],
       [ 63,  69,  80],
       [105, 114, 131]])

In [9]:
6 + A

array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [10]:
A / B

array([[0.1       , 0.2       , 0.3       ],
       [4.        , 5.        , 3.        ],
       [2.33333333, 2.        , 1.8       ]])

In [11]:
# pseudo-aleatorio

np.random.random((4, 4))

array([[0.73674591, 0.51713175, 0.54938097, 0.27479679],
       [0.99080889, 0.71565651, 0.10121803, 0.57200476],
       [0.29455016, 0.81421022, 0.41000356, 0.55757995],
       [0.72554485, 0.75767771, 0.68956051, 0.64929426]])

In [12]:
np.random.seed(1)

In [13]:
C = np.random.randint(low=1, high=11, size=(1000, 1000))
D = np.random.randint(low=1, high=11, size=(1000, 1000))

In [14]:
C.shape

(1000, 1000)

In [17]:
C * D

array([[ 24,   9, 100, ...,  35,   9,  14],
       [ 63,  36,  64, ...,  80,  30,  40],
       [  8,  40,  24, ...,  10,  18,   6],
       ...,
       [  6,  60,   4, ...,  21,  72,  14],
       [ 32,   2,   3, ...,  70,   6,  10],
       [ 16,  28,  25, ...,  50,  16,  40]])

In [16]:
C @ D

array([[29215, 29554, 31138, ..., 30160, 30305, 29815],
       [29269, 29379, 31396, ..., 30432, 30213, 29751],
       [30830, 30300, 32375, ..., 31356, 31241, 30694],
       ...,
       [30692, 30252, 31690, ..., 30948, 31099, 30590],
       [30423, 30090, 31408, ..., 31018, 31139, 30649],
       [30732, 30950, 32074, ..., 31636, 31162, 30947]])

Matrices de ceros
matrices de unos
matrices identidad

In [24]:
matriz_de_ceros = np.zeros([5, 5], dtype=np.int8)

In [25]:
type(matriz_de_ceros)

numpy.ndarray

In [26]:
matriz_de_ceros.dtype

dtype('int8')

In [27]:
matriz_de_ceros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [22]:
np.array([1,2,3,"hola", 3.13])

array(['1', '2', '3', 'hola', '3.13'], dtype='<U32')

In [29]:
np.ones([100, 100], dtype=np.int16)

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=int16)

In [32]:
np.eye(7, dtype=np.int16)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]], dtype=int16)

In [34]:
C

array([[ 6,  9, 10, ...,  5,  3,  7],
       [ 9,  6,  8, ..., 10, 10,  4],
       [ 8,  5,  4, ...,  2,  9,  1],
       ...,
       [ 2,  6,  4, ...,  7,  8,  2],
       [ 8,  1,  1, ..., 10,  3,  1],
       [ 4,  4,  5, ..., 10,  8,  4]])

In [38]:
C[0, 0]

6

In [47]:
"Hola mundo"[:]

'Hola mundo'

In [50]:
C[:3, :3]

array([[ 6,  9, 10],
       [ 9,  6,  8],
       [ 8,  5,  4]])

In [52]:
C[-3:, -3:]

array([[ 7,  8,  2],
       [10,  3,  1],
       [10,  8,  4]])